server:
  port: 8081
spring:
  datasource: # H2 DB 설정
    url: jdbc:h2:mem:BS_SVC
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true # Jpa 수행 시 SQL문 로그 출력
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE